### ISSUE TITLE
What is `SetSynchronizationContext(prevContext)` for?

### ISSUE THREAD

**Issue by Denis535** [negativeeddy/blog-examples#2]
Trace.WriteLine( "_: " + Thread.CurrentThread.ManagedThreadId + " " + (SynchronizationContext.Current != null) );

    await new NullSynchronizationContextAwaiter();
    Trace.WriteLine( "A: " + Thread.CurrentThread.ManagedThreadId + " " + (SynchronizationContext.Current != null) );

    await Task.Delay( 1000 );
    Trace.WriteLine( "B: " + Thread.CurrentThread.ManagedThreadId + " " + (SynchronizationContext.Current != null) );

    await Task.Delay( 1000 );
    Trace.WriteLine( "C: " + Thread.CurrentThread.ManagedThreadId + " " + (SynchronizationContext.Current != null) );

    public struct NullSynchronizationContextAwaiter : INotifyCompletion {

        private bool IsRequired => SynchronizationContext.Current != null;
        public bool IsCompleted => !IsRequired;

        public NullSynchronizationContextAwaiter GetAwaiter() {
            return this;
        }

        public void OnCompleted(Action continuation) {
            var prev = SynchronizationContext.Current;
            Trace.WriteLine( "{" );
            SynchronizationContext.SetSynchronizationContext( null );
            try {
                continuation();
            } finally {
                SynchronizationContext.SetSynchronizationContext( prev );
                Trace.WriteLine( "}" );
            }
        }

        public void GetResult() {
        }

    }

This code outputs:
```
_: 1 True
{
A: 1 False
}
B: 4 False
C: 4 False
```

Looks like this line `SynchronizationContext.SetSynchronizationContext( prev )` doesn't work.
if `SynchronizationContext` restoring worked then `B: 4 False, C: 4 False` were `B: 1 True, C: 1 True`. 
Or do I not understand something?

**Comment by Denis535** [comment]
I can do it without any awaiters. And I do not see any difference. Maybe I'm wrong?

        public void ResetSynchronizationContext() {
            SynchronizationContext.SetSynchronizationContext( null );
        }

**Comment by negativeeddy** [comment]
I'm seeing a difference between WPF and console apps. WPF has my described behavior. Console has yours. The difference may be that WPF has a default context whereas the console app does not.

**Comment by negativeeddy** [comment]
OK, here is the difference. The context isn't explicitly flown across awaits. The continuation is posted back to the original context and whatever happens happens. The WPF context (and most derived contexts) sets the continuation's context to itself in the post. So after the await you will see the same context. 

In console apps (and ASP.NET Core) you have the default context which just posts to the thread pool and doesn't set the context of the continuation.
```csharp
public virtual void Post(SendOrPostCallback d, object state)
{
    ThreadPool.QueueUserWorkItem(d.Invoke, state);
}
```

If you set the original context to something like this in a console app, you will see the context appear on the other side of the await.

```csharp
public class MySynchronizationContext : SynchronizationContext
{
    public override void Post(SendOrPostCallback d, object state)
    {
        ThreadPool.QueueUserWorkItem(s =>
        {
            SynchronizationContext.SetSynchronizationContext(this);
            d.Invoke(s);
        }, state);
    }
}

```
